-- 0001 · Esquema inicial de ProyectoChats.
--
-- Las migraciones se aplican en orden y una sola vez (tabla schema_migrations), con el usuario dueño del
-- esquema (DATABASE_ADMIN_URL). Una migración ya aplicada NO se modifica: los cambios van en un archivo nuevo
-- (0002_..., 0003_...). Esta es idempotente (IF NOT EXISTS) para poder adoptar bases de datos creadas antes de
-- existir las migraciones.
--
-- Fechas: TIMESTAMP sin zona; las que genera el servidor, en UTC (la conexión fija timezone=UTC).

CREATE EXTENSION IF NOT EXISTS unaccent;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_ts_config WHERE cfgname = 'es_unaccent') THEN
        CREATE TEXT SEARCH CONFIGURATION es_unaccent (COPY = spanish);
        ALTER TEXT SEARCH CONFIGURATION es_unaccent
            ALTER MAPPING FOR hword, hword_part, word WITH unaccent, spanish_stem;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    email         TEXT UNIQUE,
    username      TEXT,
    password_hash TEXT,
    role          TEXT NOT NULL DEFAULT 'user',    -- user | admin
    active        SMALLINT NOT NULL DEFAULT 1,
    theme         TEXT NOT NULL DEFAULT 'system',  -- system | light | dark
    tour_version  INTEGER NOT NULL DEFAULT 0       -- última versión del tutorial que ha visto
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON users (lower(username));

CREATE TABLE IF NOT EXISTS clients (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              TEXT NOT NULL,
    company           TEXT,
    notes             TEXT,
    status            TEXT NOT NULL DEFAULT 'active',   -- lead | active | issue | inactive
    -- Quién decidió el estado: auto (la IA o la regla de inactividad) | manual (una persona). Un cambio manual
    -- se respeta hasta que llegan mensajes nuevos (posteriores a status_last_message_id).
    status_source          TEXT NOT NULL DEFAULT 'auto',
    status_reason          TEXT,
    status_updated_at      TIMESTAMP,
    status_updated_by      BIGINT REFERENCES users(id) ON DELETE SET NULL,
    status_last_message_id BIGINT,
    assignee_user_id  BIGINT REFERENCES users(id) ON DELETE SET NULL,  -- responsable del cliente
    created_at        TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);

CREATE TABLE IF NOT EXISTS client_identities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    channel     TEXT NOT NULL,          -- email | whatsapp | telegram | phone | other
    handle      TEXT NOT NULL,          -- dirección, número, @usuario
    UNIQUE (channel, handle)
);
CREATE INDEX IF NOT EXISTS idx_identities_client ON client_identities (client_id);

CREATE TABLE IF NOT EXISTS conversations (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id             BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    owner_user_id         BIGINT NOT NULL REFERENCES users(id),
    channel               TEXT NOT NULL,
    subject               TEXT,
    -- Último mensaje del cliente marcado como "no necesita respuesta" (sale de la bandeja Sin responder).
    dismissed_message_id  BIGINT,
    -- Pospuesta hasta una fecha (UTC): sale de la bandeja hasta entonces, o hasta que el cliente vuelva a escribir.
    snoozed_until         TIMESTAMP,
    snoozed_message_id    BIGINT,
    created_at            TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);
CREATE INDEX IF NOT EXISTS idx_conv_client ON conversations (client_id, owner_user_id);

CREATE TABLE IF NOT EXISTS messages (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id  BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    direction        TEXT NOT NULL CHECK (direction IN ('in', 'out')),  -- in = escribió el cliente
    sender           TEXT NOT NULL,
    body             TEXT NOT NULL,
    sent_at          TIMESTAMP NOT NULL,    -- hora local del mensaje
    -- Identificador en su canal (Message-ID, id de Telegram/WhatsApp): evita duplicados y permite responder en hilo.
    external_id      TEXT,
    tsv              tsvector GENERATED ALWAYS AS (to_tsvector('es_unaccent', body)) STORED
);
CREATE INDEX IF NOT EXISTS idx_messages_conv ON messages (conversation_id, sent_at);
CREATE INDEX IF NOT EXISTS idx_messages_external ON messages (external_id);
CREATE INDEX IF NOT EXISTS idx_messages_tsv ON messages USING GIN (tsv);

-- Datos clave de cada cliente. origin: ai (extraído por la IA) | manual (escrito o corregido por
-- una persona; la IA nunca lo sobrescribe) | dismissed (dato de la IA descartado; no se vuelve a proponer).
CREATE TABLE IF NOT EXISTS client_facts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id          BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    label              TEXT NOT NULL,
    value              TEXT NOT NULL,
    origin             TEXT NOT NULL DEFAULT 'manual',
    source_message_id  BIGINT REFERENCES messages(id) ON DELETE SET NULL,
    updated_by         BIGINT REFERENCES users(id) ON DELETE SET NULL,
    updated_at         TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);
CREATE INDEX IF NOT EXISTS idx_client_facts ON client_facts (client_id, origin);

-- Tareas y compromisos (detectados por la IA o creados a mano).
CREATE TABLE IF NOT EXISTS tasks (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id          BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    title              TEXT NOT NULL,
    due_date           DATE,
    assignee_user_id   BIGINT REFERENCES users(id) ON DELETE SET NULL,
    status             TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'done')),
    origin             TEXT NOT NULL DEFAULT 'manual',   -- ai | manual
    source_message_id  BIGINT REFERENCES messages(id) ON DELETE SET NULL,
    created_by         BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at         TIMESTAMP NOT NULL DEFAULT localtimestamp(0),
    done_at            TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_tasks_client ON tasks (client_id, status);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks (assignee_user_id, status, due_date);

-- Último análisis con IA de cada cliente (resumen del estado y hasta qué mensaje se analizó).
CREATE TABLE IF NOT EXISTS client_analysis (
    client_id        BIGINT PRIMARY KEY REFERENCES clients(id) ON DELETE CASCADE,
    summary          TEXT NOT NULL,
    last_message_id  BIGINT,
    priority         TEXT,     -- alta | media | baja: urgencia de lo que espera el cliente
    mood             TEXT,     -- contento | neutral | molesto: tono del cliente en lo último que ha escrito
    priority_reason  TEXT,
    analyzed_at      TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);

-- Conexiones con los canales. La configuración (contraseñas, tokens) se guarda cifrada.
CREATE TABLE IF NOT EXISTS integrations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind           TEXT NOT NULL CHECK (kind IN ('email', 'telegram', 'whatsapp')),
    name           TEXT NOT NULL,
    owner_user_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    config         TEXT NOT NULL,               -- JSON cifrado
    state          TEXT NOT NULL DEFAULT '{}',  -- progreso de la sincronización (último UID, offset...)
    enabled        SMALLINT NOT NULL DEFAULT 1,
    last_sync_at   TIMESTAMP,
    last_error     TEXT,
    created_at     TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);

-- Adjuntos de mensajes y documentos subidos a la ficha (archivo en DATA_DIR/attachments).
CREATE TABLE IF NOT EXISTS attachments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    message_id      BIGINT REFERENCES messages(id) ON DELETE CASCADE,   -- NULL = subido a la ficha
    filename        TEXT NOT NULL,
    mime            TEXT NOT NULL,
    size            INTEGER NOT NULL,
    path            TEXT NOT NULL,
    extracted_text  TEXT,
    extracted_by    TEXT,          -- pdf | text | ai
    uploaded_by     BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT localtimestamp(0),
    tsv             tsvector GENERATED ALWAYS AS
                        (to_tsvector('es_unaccent', filename || ' ' || coalesce(extracted_text, ''))) STORED
);
CREATE INDEX IF NOT EXISTS idx_attachments_client ON attachments (client_id);
CREATE INDEX IF NOT EXISTS idx_attachments_message ON attachments (message_id);
CREATE INDEX IF NOT EXISTS idx_attachments_tsv ON attachments USING GIN (tsv);

-- Etiquetas libres de los clientes ("mayorista", "VIP"...); sin distinguir mayúsculas.
CREATE TABLE IF NOT EXISTS client_tags (
    client_id  BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    tag        TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_client_tags ON client_tags (client_id, lower(tag));

-- Notas internas del equipo sobre un cliente (el cliente nunca las ve).
CREATE TABLE IF NOT EXISTS client_notes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    user_id     BIGINT REFERENCES users(id) ON DELETE SET NULL,
    body        TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT localtimestamp(0),
    updated_at  TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_client_notes ON client_notes (client_id, id);

-- Avisos para cada usuario (menciones en notas, tareas asignadas...).
CREATE TABLE IF NOT EXISTS notifications (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind           TEXT NOT NULL,          -- mention | task_assigned | client_assigned
    text           TEXT NOT NULL,
    client_id      BIGINT REFERENCES clients(id) ON DELETE CASCADE,
    actor_user_id  BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT localtimestamp(0),
    read_at        TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications (user_id, read_at, id);

-- Última vez que cada usuario abrió cada cliente (para "novedades desde tu última visita" y no leídos).
CREATE TABLE IF NOT EXISTS client_visits (
    user_id          BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    client_id        BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    visited_at       TIMESTAMP NOT NULL,
    last_message_id  BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, client_id)
);

-- Seguimientos: «avísame si el cliente no contesta antes de due_at». Se resuelven solos si el cliente
-- escribe después de after_message_id.
CREATE TABLE IF NOT EXISTS follow_ups (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id   BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    user_id           BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    after_message_id  BIGINT NOT NULL,
    due_at            TIMESTAMP NOT NULL,
    created_at        TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);
CREATE INDEX IF NOT EXISTS idx_follow_ups_user ON follow_ups (user_id, due_at);

-- Dónde está cada persona ahora mismo: qué cliente tiene abierto y si está redactando una respuesta
-- (para avisar a los compañeros y no responder dos veces). Caduca si no se renueva en unos segundos.
CREATE TABLE IF NOT EXISTS presence (
    user_id    BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    client_id  BIGINT REFERENCES clients(id) ON DELETE CASCADE,
    composing  SMALLINT NOT NULL DEFAULT 0,
    seen_at    TIMESTAMP NOT NULL
);

-- Ajustes de la app que cambia un administrador (p. ej. sla_hours: plazo de respuesta).
CREATE TABLE IF NOT EXISTS app_settings (
    key    TEXT PRIMARY KEY,
    value  TEXT NOT NULL
);

-- Respuestas guardadas del equipo (plantillas con variables). Si tienen acciones (estado, etiqueta,
-- marcar atendido) funcionan como macro: al usarlas también se aplican al cliente.
CREATE TABLE IF NOT EXISTS saved_replies (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title        TEXT NOT NULL,
    shortcut     TEXT,                  -- se inserta escribiendo /atajo en el borrador
    body         TEXT NOT NULL,
    set_status   TEXT,                  -- lead | active | issue | inactive
    add_tag      TEXT,
    mark_done    SMALLINT NOT NULL DEFAULT 0,   -- quitar la conversación de «Sin responder» al enviar
    created_by   BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at   TIMESTAMP NOT NULL DEFAULT localtimestamp(0),
    updated_at   TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_saved_replies_shortcut ON saved_replies (lower(shortcut));

-- Registro de accesos y acciones delicadas (protección de datos). client_name se guarda aparte para
-- que el registro siga siendo legible aunque el cliente se borre.
CREATE TABLE IF NOT EXISTS audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action       TEXT NOT NULL,
    client_id    BIGINT,
    client_name  TEXT,
    detail       TEXT,
    created_at   TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log (created_at);

-- Intentos fallidos de inicio de sesión, para bloquear ataques de fuerza bruta.
CREATE TABLE IF NOT EXISTS login_failures (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    TEXT NOT NULL,
    ip          TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_login_failures_user ON login_failures (lower(username), created_at);
CREATE INDEX IF NOT EXISTS idx_login_failures_ip ON login_failures (ip, created_at);

-- Sesiones de inicio de sesión (se guarda el hash del token, nunca el token).
CREATE TABLE IF NOT EXISTS auth_sessions (
    token_hash  TEXT PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TIMESTAMP NOT NULL DEFAULT localtimestamp(0),
    expires_at  TIMESTAMP NOT NULL
);

-- Conversaciones con los asistentes. kind = agent (datos de clientes) | help (mascota).
-- Por cada (usuario, kind, cliente) hay una conversación activa; "Nueva conversación" archiva la actual.
CREATE TABLE IF NOT EXISTS chat_sessions (
    id            TEXT PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind          TEXT NOT NULL,
    client_id     BIGINT REFERENCES clients(id) ON DELETE CASCADE,
    archived      SMALLINT NOT NULL DEFAULT 0,
    api_messages  TEXT NOT NULL DEFAULT '[]',   -- historial exacto enviado a Claude (JSON)
    created_at    TIMESTAMP NOT NULL DEFAULT localtimestamp(0),
    updated_at    TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_owner ON chat_sessions (user_id, kind, client_id, archived);

-- Lo que se muestra en pantalla de cada conversación.
CREATE TABLE IF NOT EXISTS chat_turns (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  TEXT NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role        TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    text        TEXT NOT NULL,
    tool_calls  TEXT,                            -- JSON con las búsquedas hechas
    created_at  TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);
CREATE INDEX IF NOT EXISTS idx_chat_turns_session ON chat_turns (session_id, id);
