"""Acceso a la base de datos PostgreSQL.

Modelo de datos:
- users: miembros del equipo que usan la app.
- clients: clientes (una persona/empresa, sin importar el canal).
- client_identities: cómo se identifica el cliente en cada canal (email, WhatsApp, Telegram...).
- conversations: un hilo de un canal concreto, perteneciente a un usuario del equipo.
- messages: mensajes de cada conversación, con índice de búsqueda en español (sin tildes y por raíz:
  "entregas" encuentra "entrega").

Conexión: DATABASE_URL (en backend/.env; la crea scripts/postgres.ps1). Los archivos (adjuntos, clave de
cifrado) van en DATA_DIR (por defecto backend/data).

Compatibilidad: las consultas se escriben con `?` como marcador (se traducen a `%s`) y las fechas se
devuelven como texto ISO "AAAA-MM-DDTHH:MM:SS" (las generadas por el servidor, en UTC), igual que antes.
"""
import os
import threading
from collections.abc import Iterator
from contextlib import contextmanager
from pathlib import Path

import psycopg
from psycopg.adapt import Loader
from psycopg_pool import ConnectionPool

BASE_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = Path(os.getenv("DATA_DIR", "data"))
if not DATA_DIR.is_absolute():
    DATA_DIR = BASE_DIR / DATA_DIR
DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://proyectochats@localhost:5432/proyectochats")
TS_CONFIG = "es_unaccent"  # configuración de búsqueda: español + sin tildes

SCHEMA = """
CREATE EXTENSION IF NOT EXISTS unaccent;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_ts_config WHERE cfgname = 'es_unaccent') THEN
        CREATE TEXT SEARCH CONFIGURATION es_unaccent (COPY = spanish);
        ALTER TEXT SEARCH CONFIGURATION es_unaccent
            ALTER MAPPING FOR hword, hword_part, word WITH unaccent, spanish_stem;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          TEXT NOT NULL,
    email         TEXT UNIQUE,
    username      TEXT,
    password_hash TEXT,
    role          TEXT NOT NULL DEFAULT 'user',    -- user | admin
    active        SMALLINT NOT NULL DEFAULT 1,
    theme         TEXT NOT NULL DEFAULT 'system',  -- system | light | dark
    tour_version  INTEGER NOT NULL DEFAULT 0       -- última versión del tutorial que ha visto
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON users (lower(username));

CREATE TABLE IF NOT EXISTS clients (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              TEXT NOT NULL,
    company           TEXT,
    notes             TEXT,
    status            TEXT NOT NULL DEFAULT 'active',   -- lead | active | issue | inactive
    assignee_user_id  BIGINT REFERENCES users(id) ON DELETE SET NULL,  -- responsable del cliente
    created_at        TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);

CREATE TABLE IF NOT EXISTS client_identities (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    channel     TEXT NOT NULL,          -- email | whatsapp | telegram | phone | other
    handle      TEXT NOT NULL,          -- dirección, número, @usuario
    UNIQUE (channel, handle)
);
CREATE INDEX IF NOT EXISTS idx_identities_client ON client_identities (client_id);

CREATE TABLE IF NOT EXISTS conversations (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id             BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    owner_user_id         BIGINT NOT NULL REFERENCES users(id),
    channel               TEXT NOT NULL,
    subject               TEXT,
    -- Último mensaje del cliente marcado como "no necesita respuesta" (sale de la bandeja Sin responder).
    dismissed_message_id  BIGINT,
    created_at            TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);
CREATE INDEX IF NOT EXISTS idx_conv_client ON conversations (client_id, owner_user_id);

CREATE TABLE IF NOT EXISTS messages (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id  BIGINT NOT NULL REFERENCES conversations(id) ON DELETE CASCADE,
    direction        TEXT NOT NULL CHECK (direction IN ('in', 'out')),  -- in = escribió el cliente
    sender           TEXT NOT NULL,
    body             TEXT NOT NULL,
    sent_at          TIMESTAMP NOT NULL,    -- hora local del mensaje
    -- Identificador en su canal (Message-ID, id de Telegram/WhatsApp): evita duplicados y permite responder en hilo.
    external_id      TEXT,
    tsv              tsvector GENERATED ALWAYS AS (to_tsvector('es_unaccent', body)) STORED
);
CREATE INDEX IF NOT EXISTS idx_messages_conv ON messages (conversation_id, sent_at);
CREATE INDEX IF NOT EXISTS idx_messages_external ON messages (external_id);
CREATE INDEX IF NOT EXISTS idx_messages_tsv ON messages USING GIN (tsv);

-- Datos clave de cada cliente. origin: ai (extraído por la IA) | manual (escrito o corregido por
-- una persona; la IA nunca lo sobrescribe) | dismissed (dato de la IA descartado; no se vuelve a proponer).
CREATE TABLE IF NOT EXISTS client_facts (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id          BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    label              TEXT NOT NULL,
    value              TEXT NOT NULL,
    origin             TEXT NOT NULL DEFAULT 'manual',
    source_message_id  BIGINT REFERENCES messages(id) ON DELETE SET NULL,
    updated_by         BIGINT REFERENCES users(id) ON DELETE SET NULL,
    updated_at         TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);
CREATE INDEX IF NOT EXISTS idx_client_facts ON client_facts (client_id, origin);

-- Tareas y compromisos (detectados por la IA o creados a mano).
CREATE TABLE IF NOT EXISTS tasks (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id          BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    title              TEXT NOT NULL,
    due_date           DATE,
    assignee_user_id   BIGINT REFERENCES users(id) ON DELETE SET NULL,
    status             TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'done')),
    origin             TEXT NOT NULL DEFAULT 'manual',   -- ai | manual
    source_message_id  BIGINT REFERENCES messages(id) ON DELETE SET NULL,
    created_by         BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at         TIMESTAMP NOT NULL DEFAULT localtimestamp(0),
    done_at            TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_tasks_client ON tasks (client_id, status);
CREATE INDEX IF NOT EXISTS idx_tasks_assignee ON tasks (assignee_user_id, status, due_date);

-- Último análisis con IA de cada cliente (resumen del estado y hasta qué mensaje se analizó).
CREATE TABLE IF NOT EXISTS client_analysis (
    client_id        BIGINT PRIMARY KEY REFERENCES clients(id) ON DELETE CASCADE,
    summary          TEXT NOT NULL,
    last_message_id  BIGINT,
    analyzed_at      TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);

-- Conexiones con los canales. La configuración (contraseñas, tokens) se guarda cifrada.
CREATE TABLE IF NOT EXISTS integrations (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind           TEXT NOT NULL CHECK (kind IN ('email', 'telegram', 'whatsapp')),
    name           TEXT NOT NULL,
    owner_user_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    config         TEXT NOT NULL,               -- JSON cifrado
    state          TEXT NOT NULL DEFAULT '{}',  -- progreso de la sincronización (último UID, offset...)
    enabled        SMALLINT NOT NULL DEFAULT 1,
    last_sync_at   TIMESTAMP,
    last_error     TEXT,
    created_at     TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);

-- Adjuntos de mensajes y documentos subidos a la ficha (archivo en DATA_DIR/attachments).
CREATE TABLE IF NOT EXISTS attachments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id       BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    message_id      BIGINT REFERENCES messages(id) ON DELETE CASCADE,   -- NULL = subido a la ficha
    filename        TEXT NOT NULL,
    mime            TEXT NOT NULL,
    size            INTEGER NOT NULL,
    path            TEXT NOT NULL,
    extracted_text  TEXT,
    extracted_by    TEXT,          -- pdf | text | ai
    uploaded_by     BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT localtimestamp(0),
    tsv             tsvector GENERATED ALWAYS AS
                        (to_tsvector('es_unaccent', filename || ' ' || coalesce(extracted_text, ''))) STORED
);
CREATE INDEX IF NOT EXISTS idx_attachments_client ON attachments (client_id);
CREATE INDEX IF NOT EXISTS idx_attachments_message ON attachments (message_id);
CREATE INDEX IF NOT EXISTS idx_attachments_tsv ON attachments USING GIN (tsv);

-- Etiquetas libres de los clientes ("mayorista", "VIP"...); sin distinguir mayúsculas.
CREATE TABLE IF NOT EXISTS client_tags (
    client_id  BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    tag        TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_client_tags ON client_tags (client_id, lower(tag));

-- Notas internas del equipo sobre un cliente (el cliente nunca las ve).
CREATE TABLE IF NOT EXISTS client_notes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id   BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    user_id     BIGINT REFERENCES users(id) ON DELETE SET NULL,
    body        TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT localtimestamp(0),
    updated_at  TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_client_notes ON client_notes (client_id, id);

-- Avisos para cada usuario (menciones en notas, tareas asignadas...).
CREATE TABLE IF NOT EXISTS notifications (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind           TEXT NOT NULL,          -- mention | task_assigned | client_assigned
    text           TEXT NOT NULL,
    client_id      BIGINT REFERENCES clients(id) ON DELETE CASCADE,
    actor_user_id  BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at     TIMESTAMP NOT NULL DEFAULT localtimestamp(0),
    read_at        TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications (user_id, read_at, id);

-- Última vez que cada usuario abrió cada cliente (para "novedades desde tu última visita" y no leídos).
CREATE TABLE IF NOT EXISTS client_visits (
    user_id          BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    client_id        BIGINT NOT NULL REFERENCES clients(id) ON DELETE CASCADE,
    visited_at       TIMESTAMP NOT NULL,
    last_message_id  BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, client_id)
);

-- Registro de accesos y acciones delicadas (protección de datos). client_name se guarda aparte para
-- que el registro siga siendo legible aunque el cliente se borre.
CREATE TABLE IF NOT EXISTS audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT REFERENCES users(id) ON DELETE SET NULL,
    action       TEXT NOT NULL,
    client_id    BIGINT,
    client_name  TEXT,
    detail       TEXT,
    created_at   TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_log (created_at);

-- Intentos fallidos de inicio de sesión, para bloquear ataques de fuerza bruta.
CREATE TABLE IF NOT EXISTS login_failures (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    TEXT NOT NULL,
    ip          TEXT NOT NULL,
    created_at  TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_login_failures_user ON login_failures (lower(username), created_at);
CREATE INDEX IF NOT EXISTS idx_login_failures_ip ON login_failures (ip, created_at);

-- Sesiones de inicio de sesión (se guarda el hash del token, nunca el token).
CREATE TABLE IF NOT EXISTS auth_sessions (
    token_hash  TEXT PRIMARY KEY,
    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at  TIMESTAMP NOT NULL DEFAULT localtimestamp(0),
    expires_at  TIMESTAMP NOT NULL
);

-- Conversaciones con los asistentes. kind = agent (datos de clientes) | help (mascota).
-- Por cada (usuario, kind, cliente) hay una conversación activa; "Nueva conversación" archiva la actual.
CREATE TABLE IF NOT EXISTS chat_sessions (
    id            TEXT PRIMARY KEY,
    user_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    kind          TEXT NOT NULL,
    client_id     BIGINT REFERENCES clients(id) ON DELETE CASCADE,
    archived      SMALLINT NOT NULL DEFAULT 0,
    api_messages  TEXT NOT NULL DEFAULT '[]',   -- historial exacto enviado a Claude (JSON)
    created_at    TIMESTAMP NOT NULL DEFAULT localtimestamp(0),
    updated_at    TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);
CREATE INDEX IF NOT EXISTS idx_chat_sessions_owner ON chat_sessions (user_id, kind, client_id, archived);

-- Lo que se muestra en pantalla de cada conversación.
CREATE TABLE IF NOT EXISTS chat_turns (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  TEXT NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
    role        TEXT NOT NULL CHECK (role IN ('user', 'assistant')),
    text        TEXT NOT NULL,
    tool_calls  TEXT,                            -- JSON con las búsquedas hechas
    created_at  TIMESTAMP NOT NULL DEFAULT localtimestamp(0)
);
CREATE INDEX IF NOT EXISTS idx_chat_turns_session ON chat_turns (session_id, id);
"""


# ---------------------------------------------------------------- Tipos: fechas como texto ISO

class _TimestampLoader(Loader):
    """TIMESTAMP -> "AAAA-MM-DDTHH:MM:SS" (sin fracciones de segundo)."""

    def load(self, data):
        return bytes(data[:19]).decode().replace(" ", "T")


class _DateLoader(Loader):
    def load(self, data):
        return bytes(data).decode()


class Row(dict):
    """Fila accesible por nombre (row["name"]) y por posición (row[0])."""

    def __getitem__(self, key):
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


def _row_factory(cursor):
    names = [c.name for c in cursor.description] if cursor.description else []
    return lambda values: Row(zip(names, values))


def _configure(conn: psycopg.Connection) -> None:
    conn.adapters.register_loader("timestamp", _TimestampLoader)
    conn.adapters.register_loader("date", _DateLoader)


# ---------------------------------------------------------------- Conexiones

class Cursor:
    def __init__(self, cur):
        self._cur = cur

    def __iter__(self):
        return iter(self._cur)

    def __getattr__(self, name):
        return getattr(self._cur, name)

    @property
    def lastrowid(self):
        """Id insertado: la sentencia debe terminar en RETURNING id."""
        return self._cur.fetchone()[0]


def _sql(sql: str) -> str:
    # Marcadores "?" (estilo de la versión anterior) -> "%s"; los "%" literales se escapan.
    return sql.replace("%", "%%").replace("?", "%s")


class Conn:
    def __init__(self, raw: psycopg.Connection):
        self.raw = raw

    def execute(self, sql: str, params=None) -> Cursor:
        cur = self.raw.cursor(row_factory=_row_factory)
        if params is None or len(params) == 0:
            cur.execute(sql)
        else:
            cur.execute(_sql(sql), list(params))
        return Cursor(cur)

    def executemany(self, sql: str, seq) -> None:
        seq = [list(p) for p in seq]
        if seq:
            self.raw.cursor().executemany(_sql(sql), seq)


_pool: ConnectionPool | None = None
_pool_lock = threading.Lock()


def _get_pool() -> ConnectionPool:
    global _pool
    with _pool_lock:
        if _pool is None:
            _pool = ConnectionPool(DATABASE_URL, min_size=1, max_size=int(os.getenv("DB_POOL_SIZE", "10")),
                                   kwargs={"options": "-c timezone=UTC"}, configure=_configure, open=True)
    return _pool


@contextmanager
def get_conn() -> Iterator[Conn]:
    """Conexión del pool para una operación: commit al terminar, rollback si hay error."""
    with _get_pool().connection() as raw:
        yield Conn(raw)


def init_db() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with get_conn() as conn:
        conn.raw.execute(SCHEMA)


def reset_db() -> None:
    """Borra TODAS las tablas y datos y vuelve a crear el esquema (datos de ejemplo y pruebas)."""
    with get_conn() as conn:
        conn.raw.execute("DROP SCHEMA public CASCADE; CREATE SCHEMA public;")
    init_db()


def rows(cursor) -> list[dict]:
    return [dict(r) for r in cursor.fetchall()]
